source "https://rubygems.org"

ruby '2.4.0'

gem 'sinatra'
gem 'sinatra-flash'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'rake'

group :test do
  gem 'byebug'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'rspec'
  gem 'rspec-sinatra'
  gem 'selenium-webdriver'
end
